[package]
name = "cuda"
version = "0.1.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
license = "BSD-2-Clause"
description = "CUDA API bindings."
repository = "https://github.com/peterhj/libcuda"
keywords = ["cuda"]

[dependencies]
libc = "^0.2"

[lib]
name = "cuda"
path = "src/lib.rs"
